### PR TITLE
Replaced div as tab list container instead of ul

### LINKED ISSUE #35: Use a div as tab list container instead of ul
We used list for the tab list earlier but now we have wrapped each element inside a particular div. So the `ul` tag is redundant now cause we are not using html list for tab list ( pretty ironic xD ). We need to update the `ul` container to a `div` with suitable class name and properties.

### PR DESCRIPTION
**Pull request by aadishjain08**
Resolved #35

### CODE REVIEW

**Comment by daemon1024** [comment]
Hey @aadishjain08, Thanks a lot for the PR.

Have you tested it out and can you attach screenshots if things are still working as expected?

I see that this is your first pull request on Github, Congrats 🎉 Really appreciate your contribution to TabuRei.

Just a small suggestion, currently "Resolved #35" is part of Pull Request Title but it should be part of the Pull Request Comment instead, this will automatically link the issues together with this. Reference https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

**Comment by aadishjain08** [comment]
Thanks a lot for your appreciation.
PFA the ss for tab manager of Taburei.
[](url
Screenshot (2)
)

**Review by akshgpt7 — APPROVED** [review]
LGTM

**Review by daemon1024 — APPROVED** [review]

**Review by aayushmau5 — APPROVED** [review]

**Comment by daemon1024** [comment]
Yohooo 🎉 Thanks for the contribution once again. Looking forward to many more 😄

**Pull request merged**
