### PR TITLE
added screenshots in readme

### PR DESCRIPTION
**Pull request by aryanploxxx**
Created a 'Screenshots' folder to save the screenshots of 'Taburei' and added them in the 'readme.md' file.

### CODE REVIEW

**Review by aaryanporwal — APPROVED** [review]
LGTM. Thanks for the PR
Also please link this PR to #50 , for reference read this: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

**Comment by aryanploxxx** [comment]
resolved #50

**Comment by daemon1024** [comment]
Fixes #50

**Comment by daemon1024** [comment]
image

this looks a bit inconsistent imo

Should we instead record a GIF and add it?
What do you think @aaryanporwal

**Comment by aaryanporwal** [comment]
Maybe a description of the screenshots instead of just having a heading "Screenshots" for now is fine. 
But surely I think a recording of the app is much more sustainable.

**Pull request closed without merging**
