### PR TITLE
Adding option to Export tabs

### LINKED ISSUE #40: Add option to Export tabs from Taburei
There should be an option to Export all the tabs/groups in plain text.

Suggested Format:
```
<group-name>
<url> - <tab-name>
```

### PR DESCRIPTION
**Pull request by osBins**
Fixes #40

### CODE REVIEW

**Comment by osBins** [comment]
@daemon1024 the 'export' option is functioning now. Let me know if anything needs to be changed or added.

**Comment by daemon1024** [comment]
Can ya share screenshot/screenrecord for this?

**Comment by osBins** [comment]
image
image

**Comment by daemon1024** [comment]
Noice work 😀. 

The text field looks off center! Can you look into it?

 Also I am wondering if we can add CSS to text field to match with the rest of the color scheme.

**Comment by osBins** [comment]
image
Let me know if this looks fine. I'll push the changes

**Comment by daemon1024** [comment]
But of internal padding maybe, rest lgtm

**Comment by osBins** [comment]
Added internal padding of 12px to the textarea and pushed the changes^^

**Review by akshgpt7 — COMMENTED** [review]
Good work! 
I was just thinking if we could name the "Export" button to "Export to OneTab" (since Export in itself doesn't really tell much), or otherwise, on the Export page, add a little description that you can copy the generated text to transfer your tabs to OneTab.
Rest LGTM.

**Review by aayushmau5 — APPROVED** [review]
LGTM. Good Work :rocket:

**Comment by aayushmau5** [comment]
> I was just thinking if we could name the "Export" button to "Export to OneTab" (since Export in itself doesn't really tell much), or otherwise, on the Export page, add a little description that you can copy the generated text to transfer your tabs to OneTab.

How about "Export tabs" or "Export URLs" and have a little description that "this format is onetab compatible or something"?

**Comment by daemon1024** [comment]
Yeah a little description would be great.

**Comment by osBins** [comment]
Sure thing!
image
image
Let me know if the instructions need to be framed differently.

**Comment by daemon1024** [comment]
1. Don't keep any subtext near button. 

2. I don't think we need to explicitly tell how to import on OneTab. Like we don't want others to leave xD. Just a normal mention would be fine.

> The below exported list is compatible with other tab managers like OneTab

Perhaps can be framed better

**Comment by akshgpt7** [comment]
"Copy the following generated list into other tab managers like OneTab to import your tabs there:"

**Comment by daemon1024** [comment]
Not only OneTab tho? Perhaps they want to switch to a different device and import it there In TabuRei itself

**Comment by osBins** [comment]
How does
"Exported tabs below can be imported into other tab-managing extensions by copying and pasting in their 'Import URLs' section."
sound?

**Comment by daemon1024** [comment]
> .... into TabuRei and other Tab-Managinv exten........

**Comment by akshgpt7** [comment]
Don't use "Exported tabs", it makes it confusing. Just write"the following generated list", rest is fine.

**Comment by osBins** [comment]
image
image

**Comment by osBins** [comment]
Done

**Review by daemon1024 — APPROVED** [review]

**Pull request merged**
